### ISSUE TITLE
Estructuras básicas

### ISSUE THREAD

**Issue by Asmilex** [Balrrach/Instant-Eat#13]
Es necesario crear unas estructuras básicas para comenzar con el desarrollo. En particular: 
- Una clase que gestione los diferentes lugares 
- Una clase que organice estas organizaciones
- Una clase que gestione las rutas
- Estructuras para organizar pedidos y productos
- Una clase que represente al repartidor

Afecta a los HUs #8, #4, #3 y #2.

**Comment by JJ** [comment]
Este issue no plantea un problema, y además deberías dividirlo en diferentes issues, cada uno de los cuales tratara con un problema diferente.

**Comment by JJ** [comment]
Cada clase es un problema que debería plantearse en issues diferentes.
