### ISSUE TITLE
PUT siempre se hace sobre un URI

### ISSUE THREAD

**Issue by JJ** [Balrrach/Instant-Eat#40]
Porque se supone que es idempotente. ¿Cómo va a serlo si en cada `PUT` se devuelve un URI diferente?

https://github.com/Balrrach/Instant-Eat/blob/6db2eba5c6112400bea99f8ea1460230375081d5/docs/api.md?plain=1#L21

**Comment by Balrrach** [comment]
El motivo por el que lo he hecho así es porque pensaba incluir el identificador en el cuerpo o en el query de la petición puesto que en un PUT estos nunca están vacíos a diferencia de un GET, o de un DELETE en los que solo interesa el identificador.

**Comment by JJ** [comment]
PUT se hace sobre un URI. En el cuerpo puedes incluir lo que quieras (el ID también si quieres), pero esa es la regla aceptada.
